### ISSUE TITLE
Options.albumsText is not used on back navigation button

### ISSUE THREAD

**Issue by hosikiti** [NativeScript/nativescript-imagepicker#144]
Even if `options.albumsText` is set, normal label, "Albums" is shown on navigation back button of camera roll.

I found following line which might be a cause:

https://github.com/NativeScript/nativescript-imagepicker/blob/23c75d477ca111e6fe4bb95828feb9a1494bce0b/src/images.xml#L7

Confirmed on iOS only.

**Comment by tsonevn** [comment]
Hi @hosikiti,
I tested your case, however, the `albumsText` option seems to work as expected and the ActionBar title is changed properly for the first view, which is opened after the create method is called. I tested this case while using the demo app from the plugin's repository and add the following changes:
```
export function onSelectSingleTap(args) {
    let context = imagepicker.create({ mode: "single", albumsText:"Test", cancelText:"Go back" });
    startSelection(context, true);
}
```
For your convenience, I am attaching Gif file, which demonstrates the case. Also if you need to change the text for the back button, you should use `cancelText` option.
![screencast 2018-01-10 at 8 34 03 am](https://user-images.githubusercontent.com/17448734/34758957-0178a93e-f5e2-11e7-9a8a-3865a3c4f039.gif)

**Comment by hosikiti** [comment]
@tsonevn Thank you. As you said, the action bar title on the first view is changed correctly. 

In this example, I set "アルバム"(meaning albums in Japanese) to option.albumsText.

![iphone_8_-_11_2](https://user-images.githubusercontent.com/1973308/34759521-3884724a-f61f-11e7-9218-864796668b5d.jpg)

If I navigate to the image list view, a back button's label on the view is not changed properly:

![iphone_8_-_11_2](https://user-images.githubusercontent.com/1973308/34759560-6cc8bd18-f61f-11e7-8352-4b4b7e11f08d.jpg)

**Comment by tsonevn** [comment]
Hi @hosikiti,
Thank you for the attached screenshots. I tested again and indeed the NavigationButton title will be changed only for the first View and will not be respected for the next.  I will log this as a bug. For now, I would suggest keeping track on the issue for further info.
Also, any PR  will be highly appreciated. Regarding that, you could also review our [contributing guidelines](https://www.nativescript.org/contribute).

**Comment by tbozhikov** [comment]
Hi guys, @hosikiti , the [latest version](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v6.0.0) of the imagepicker plugin now uses the [QBImagePicker](https://github.com/questbeat/QBImagePicker) cocoa pod for iOS, adding some features, fixing bugs and adding very "native" looks. 
Unfortunately, this library does not allow for customizing the Labels at the top of the picker's page, so "albumsText" is no longer relevant option. On the bright side however, if you want to display some hint to the users while choosing images, you can use the `prompt` option like:
`imagepicker.create({ mode: "single", prompt: "Please choose an image" });`

The result:
<img width="284" alt="n3rco4pg-a18amibk15hoqxt9zwxsakiekd45m41zojlvwjesalj-bqlhtzmilyxqhsn-klrcz92nn3t8a5jet0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://user-images.githubusercontent.com/5127806/38738295-74be2940-3f3a-11e8-83f0-bb827a0b4456.png">

Hope this helps. I am now closing this issue since it is no longer relevant. Let us know if you have any other questions.
