### ISSUE TITLE
Cannot get FileUrl for android.os.Build.VERSION.SDK_INT >= 23

### ISSUE THREAD

**Issue by NicoleZA** [NativeScript/nativescript-imagepicker#29]
This plugin does not seem to working for android version 23.
Cannot get FileUrl

**Comment by PanayotCankov** [comment]
I've reproduced a problem that throws:
```
JS: Error: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=2346, uid=10054 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
```
Perhaps we should investigate any additional permissions that may be required when accessing files.
What files do you upload? The above was reproduced trying to upload an image selected with the nativescript-imagepicker.

**Comment by NicoleZA** [comment]
I am just picking any file from my gallery on my phone.
I have tried added different permissions but was unable to figure this one out

**Comment by PanayotCankov** [comment]
We will check if we can integrate this in the plugin, although the permission is required at the time you try to read the file, not the time you pick the image.

You can try to ask for the permission using the following plugin:
https://www.npmjs.com/package/nativescript-permissions

**Comment by PanayotCankov** [comment]
fileUri will always be unreliable in both platforms, in some cases there would be insufficient permissions, in others, the images may be still in the cloud and have yet to be downloaded. Please use `getImage` and `getImageData`. We are currently working toward making fileUri return simple null instead of crashing. After obtaining and image you can save it in you app temp files for further usage.
