### ISSUE TITLE
Permission issue on ios

### ISSUE THREAD

**Issue by xerotolerant** [NativeScript/nativescript-imagepicker#35]
Hello. The plugin seems to work properly selecting the file however the returned image cannot be used.
The resulting error is:
`fileUri: file:///var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG
`
`CONSOLE LOG file:///app/main-page.js:78:20: NSErrorWrapper: You don’t have permission to save the file “100APPLE” in the folder “DCIM”.
`

**Comment by tsonevn** [comment]
Hi @xerotolerant, 

Could you give us some more info about your problem. It would also help if you could provide sample code, where the problem could be reproduced. Regarding to that you could use `fileUri` to access the image from `Camera Roll`.

I look forward of hearing from you.

**Comment by vagabond92** [comment]
This issue is related to the fact that on ios it returns the fileUri, "file:///var/mobile/Media/DCIM/100APPLE/IMG_0002.JPG". If you strip "file://" from this, it points to the file path, and iOS will correctly access the file. On android 7.0, the fileUri is just the full path to the file. When I try to use it on an android 5.0.1 device, the imagepicker crashes when I try to access selection[index].fileUri with the following dump:

JS: ImageRankerService::select_photos: Caught image picker exception: Error: java.lang.IllegalArgumentException: Invalid URI: content://media/external/images/media/32
JS:     android.provider.DocumentsContract.getDocumentId(DocumentsContract.java:752)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:716)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:697)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:687)
JS:     com.tns.NativeScriptActivity.onActivityResult(android.app.Activity.java)
JS:     android.app.Activity.dispatchActivityResult(Activity.java:6549)
JS:     android.app.ActivityThread.deliverResults(ActivityThread.java:4084)
JS:     android.app.ActivityThread.handleSendResult(ActivityThread.java:4131)
JS:     android.app.ActivityThread.access$1400(ActivityThread.java:179)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:145)
JS:     android.app.ActivityThread.main(ActivityThread.java:5972)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

It appears that imagepicker is trying to store the same thing that appears in selection[index].uri, which is not a valid fileUri.

**Comment by vagabond92** [comment]
Turns out that my issue above re: content://media/external... was related to my using an older version of the plugin. That issue is fixed.
